### ISSUE TITLE
你好作者

### ISSUE THREAD

**Issue by zhangyiyan001** [ShuGuoJ/SSLstm#1]
关于您代码中数据集的路径索引比较复杂，可否上传一下您使用的数据集呢，非常感谢

**Comment by zhangyiyan001** [comment]
info = DatasetInfo.info[datasetName]
    data_path = "data/{0}/{0}.mat".format(datasetName)
    assert isExist(data_path)
    data = loadmat(data_path)[info['data_key']]
    label_path = "trainTestSplit/{}/sample{}_run{}.mat".format(datasetName, sample_per_class, run)
    assert isExist(label_path)
    _, testLabel = loadLabel(label_path)
尤其是上述data_path和label_path路径这块，谢谢

**Comment by ShuGuoJ** [comment]
因为数据集太多，无法上传到github，我发一个关于“sample10_run0.mat”的示例（采样自KSC数据集）给你，你照着生成就可以了。其中10的意思是每类训练样本有10个，而0则代表是第几次实验。在实验中，我们重复采样了10次。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ShuGuoJ/SSLstm"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月8日(星期天) 晚上8:39
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [ShuGuoJ/SSLstm] 你好作者 (#1)





 
info = DatasetInfo.info[datasetName]
 data_path = "data/{0}/{0}.mat".format(datasetName)
 assert isExist(data_path)
 data = loadmat(data_path)[info['data_key']]
 label_path = "trainTestSplit/{}/sample{}_run{}.mat".format(datasetName, sample_per_class, run)
 assert isExist(label_path)
 _, testLabel = loadLabel(label_path)
 尤其是上述data_path和label_path路径这块，谢谢
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zhangyiyan001** [comment]
非常感谢，我们平时对数据的预处理通常是只对Indian_pines_corrcted.mat(总数据)和Indian_pines_gt.mat(总标签)进行读取，对于训练集和测试集的划分都是在数据导入进来后再划分，您是直接在mat文件时就已经对训练集和测试集进行划分。您可以把实例上传至github，感谢

**Comment by ShuGuoJ** [comment]
您是说所有已划分的数据集吗？如果确实需要，我可以提供代码。由于github上面有最大限制，所以无法全部完整地上传数据。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ShuGuoJ/SSLstm"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月8日(星期天) 晚上8:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ShuGuoJ/SSLstm] 你好作者 (#1)





 
非常感谢，我们平时对数据的预处理通常是只对Indian_pines_corrcted.mat(总数据)和Indian_pines_gt.mat(总标签)进行读取，对于训练集和测试集的划分都是在数据导入进来后再划分，您是直接在mat文件时就已经对训练集和测试集进行划分。您可以把实例上传至github，感谢
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zhangyiyan001** [comment]
不用所有的，麻烦您可以给我划分好的Salinas数据集的样例，能否上传github,不行的话另外只是我的qq邮箱:495701023@qq.com
